### ISSUE TITLE
Typed struct or not?

### ISSUE THREAD

**Issue by hlongvu** [metachaos-systems/ccxtex#1]
I am using this library with updated  ccxt: ^1.18.418. When request **kraken** fetch_markets, the error below is throwned.

```
 (KeyError) key :altname not found in: %Ccxtex.Market{active: true, base: nil, base_id: nil, id: nil, info: nil, limits: nil, precision: nil, quote: nil, quote_id: nil, symbol: nil, symbol_id: nil}
    (stdlib) :maps.update(:altname, "ADACAD", %Ccxtex.Market{active: true, base: nil, base_id: nil, id: nil, info: nil, limits: nil, precision: nil, quote: nil, quote_id: nil, symbol: nil, symbol_id: nil})
```
The problem is Market json result for **kraken** have an unknown property **:altname** (there are some more other unknown properties)

Should we using TypedStruct for these models? Because javascript is very dynamic, the ccxt library will add more unknown properties to their results, different in various exchange, and these error will surface.

**Comment by ontofractal** [comment]
Hi @hlongvu! Thanks for opening the issue. As ccxt library standardizes the fields for API call responses, I think that typedstruct is a valid approach here. 

I've added new fields and a test for your usecase(kraken fetch_market call) and published a new version. Let me know if there is anything else. Cheers!
